title:        "Meredith M Myers"
tagline:      ""
url:          ""
author:
  name:       "Meredith M Myers"
  email:      ""
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
